### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by DumbergerL** [5pm-HDH/churchtools-api#108] opened 2022-09-12 05:10 UTC
**Error in PersonUpdateRequestTest:** ❌
Response for this Integration Test:
```json
{
  "message": "Forbidden to edit the field statusId",
  "translatedMessage": "Keine Berechtigung um das Feld statusId zu sehen oder zu editieren",
  "messageKey": "error.forbidden.edit.field",
  "args": {
    "field": "statusId"
  },
  "errors": []
}
```
- [x] Prevent "statusId" from being sent to updateRequest
- [x] Write the message and translatedMessage to the CTPermissionException for better readability 

@naitsirch Do you run into the same issue with this Integration-Test? How we can handle this Error? Should we create a "blacklist" for update attributes? Or split the `getModifiableAttributes` into `getModifiableAttributesUpdate` and `getModifiableAttributesCreate`?

**Comment by naitsirch** [comment] 2022-09-12 11:28
The issue is with the permissions setting of your user. I had the same error. But after my user account was assigned to a more privileged role, it worked ;-)

**Comment by DumbergerL** [comment] 2022-09-12 11:49
Alright! Thanks for your fast reply. Then i close the bug and just update the integration-test!

**Closed** 2022-09-12 11:49 UTC
Labels: bug, high prio
